AllCops:
  NewCops: enable
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
