#!/usr/bin/env ruby
# Turns the probe reports into the fixture the mock replays.
#
# `probe-reports/` is gitignored and exists nowhere else — it holds a device id and a serial number,
# and most of its 70 kB is a force curve nothing reads. What the tests need from it is much smaller:
# the notification frames, in the order the erg sent them, with the identity stripped. That derived
# file IS committed, because the point of building the mock out of captured bytes is lost if CI
# cannot run it.
#
# Usage: ruby scripts/extract_pm5_capture.rb   (from the repo root, with probe-reports/ present)

require 'json'
require 'time'

ROOT = File.expand_path('..', __dir__)
REPORTS = File.join(ROOT, 'probe-reports')
OUTPUT = File.join(ROOT, 'public', 'js', 'pm5-capture.js')

# The serial number characteristic, and only that one: model, firmware and manufacturer say what
# kind of machine this is, which is the useful half, and identify nobody.
SERIAL_NUMBER = 'ce060012-43e5-11e4-916c-0800200c9a66'.freeze

# Two of the three reports. The first is thirty seconds of an idle erg, which the other two both
# open with anyway.
SESSIONS = {
  'fixed-100m' => {
    file: 'pm5-20260831-224924.json',
    description: 'A single fixed 100 m piece rowed to the end: idle, twelve strokes, then the ' \
                 'split and summary a finished piece emits.'
  },
  'interval-500m' => {
    file: 'pm5-20260831-223836.json',
    description: 'The opening of a 500 m / 1 min rest interval workout. No split and no summary: ' \
                 'the PM5 reports a split only once the next one opens.'
  }
}.freeze

def characteristics(report)
  report['services'].flat_map { |service| service['characteristics'] }
end

# Both ends of every stream: `packets` holds the opening frames, which show the resting state, and
# `recent` a rolling window of the last ones, which is where the load actually is.
def notifications(characteristic)
  (characteristic['packets'].to_a + characteristic['recent'].to_a).map do |packet|
    { at: Time.iso8601(packet['at']), uuid: characteristic['uuid'], hex: packet['hex'] }
  end
end

# In the order the erg sent them, across every characteristic at once: the capture is one stream,
# and replaying each characteristic on its own clock would let the frames that close a piece arrive
# before the strokes that earned them.
def frames_from(report)
  frames = characteristics(report).flat_map { |characteristic| notifications(characteristic) }
                                  .sort_by { |frame| frame[:at] }
  origin = frames.first[:at]
  frames.map { |frame| frame.merge(at: ((frame[:at] - origin) * 1000).round) }
end

def reads_from(report)
  characteristics(report)
    .reject { |characteristic| characteristic['uuid'] == SERIAL_NUMBER }
    .select { |characteristic| characteristic['read'] }
    .to_h { |characteristic| [characteristic['uuid'], characteristic['read']['hex']] }
end

def session_literal(name, session)
  frames = session[:frames].map { |f| "      { at: #{f[:at]}, uuid: '#{f[:uuid]}', hex: '#{f[:hex]}' }" }
  reads = session[:reads].map { |uuid, hex| "      '#{uuid}': '#{hex}'" }
  <<~JS.rstrip
    '#{name}': {
        description:
          '#{session[:description]}',
        reads: {
    #{reads.join(",\n")}
        },
        frames: [
    #{frames.join(",\n")}
        ]
      }
  JS
end

sessions = SESSIONS.filter_map do |name, meta|
  path = File.join(REPORTS, meta[:file])
  unless File.exist?(path)
    warn "skipping #{name}: #{path} is missing"
    next
  end
  report = JSON.parse(File.read(path))
  [name, { description: meta[:description], reads: reads_from(report), frames: frames_from(report) }]
end.to_h

if sessions.empty?
  abort 'No probe report found — probe-reports/ is gitignored, and only exists on the machine that captured it.'
end

File.write(OUTPUT, <<~JS)
  /**
   * What the PM5 said, on 31 August 2026, byte for byte.
   *
   * GENERATED by scripts/extract_pm5_capture.rb from probe-reports/, which is gitignored and exists
   * nowhere else: re-capturing it means being in Paris in front of the erg. This file is the part
   * the tests need — the notification frames in the order they arrived, with the device id and the
   * serial number left behind — and it is committed so that the mock replays real bytes even on a
   * runner that has never seen the machine.
   *
   * `at` is milliseconds from the first frame of the session. Do not edit by hand.
   */

  export const CAPTURES = {
    #{sessions.map { |name, session| session_literal(name, session) }.join(",\n  ")}
  }

  export default CAPTURES
JS
puts "Wrote #{OUTPUT}"
sessions.each { |name, session| puts "  #{name}: #{session[:frames].length} frames" }
